name: Changelog Generator

on:
  push:
    branches: [ changelog-generator ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Make sure cache folder exists
      run: mkdir -p .cache
    
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: .cache
        key: changelog
        
    - name: Generate changelog content
      uses: browniebroke/action-github-changelog-generator@patch-2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        cacheFile: .cache/github-changelog-cache
        cacheLog: .cache/github-changelog-logger.log
        unreleased: true
        unreleasedLabel: "On master:"
        author: true
        issues: false
        pullRequests: true
        prWoLabels: false
        compareLink: true
        excludeLabels: update
        output: docs/source/changelog.md
        addSections: '{"doc":{"prefix":"**Documentation updates:**","labels":["docs"]}}'


    - name: Check that everything worked
      run: |
        git status
        
    - name: Commit changes
      run: |
        if [ -n "$(git status --short)" ]
        then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Changelog" -a
        else
          echo "No changes to commit - skipping"
        fi

    - name: Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: changelog-generator
