name: Changelog Generator

on:
  push:
    branches: [ changelog-generator ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate changelog content
      uses: CharMixer/auto-changelog-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Write output to CHANGELOG.md
      run: |
        echo ${{ steps.generate-changelog.outputs.changelog }} > CHANGELOG.md
        cat CHANGELOG.md
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update Changelog" -a

    - name: Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: changelog-generator
