name: Changelog Generator

on:
  push:
    branches: [ changelog-generator ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: push
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update Changelog'
        files: CHANGELOG.md
